## Download data base

In [ ]:
wget -O chembl_30_sqlite.tar.gz https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_30_sqlite.tar.gz

In [ ]:
# at farm
# download checksums file
wget -O db30_chechsums.txt https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/checksums.txt

In [ ]:
!cat db30_checksums.txt

In [ ]:
!sha256sum chembl_30_sqlite.tar.gz

In [ ]:
# decompress
tar -xzvf chembl_30_sqlite.tar.gz

## Import required modules

In [28]:
import pandas as pd
pd.set_option('display.max_rows', 600)
import numpy as np
import sqlite3

## Connect to the downloaded database

In [2]:
con = sqlite3.connect('chembl_30.db')
cur = con.cursor()

In [3]:
cur. execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cur.fetchall())

[('assay_type',), ('chembl_id_lookup',), ('target_type',), ('go_classification',), ('atc_classification',), ('source',), ('action_type',), ('variant_sequences',), ('protein_classification',), ('activity_smid',), ('irac_classification',), ('bioassay_ontology',), ('structural_alert_sets',), ('relationship_type',), ('confidence_score_lookup',), ('curation_lookup',), ('assay_classification',), ('data_validity_lookup',), ('products',), ('patent_use_codes',), ('research_stem',), ('hrac_classification',), ('component_sequences',), ('domains',), ('bio_component_sequences',), ('protein_family_classification',), ('version',), ('activity_stds_lookup',), ('frac_classification',), ('usan_stems',), ('organism_class',), ('target_dictionary',), ('molecule_dictionary',), ('docs',), ('protein_class_synonyms',), ('structural_alerts',), ('cell_dictionary',), ('tissue_dictionary',), ('product_patents',), ('component_synonyms',), ('component_domains',), ('research_companies',), ('component_go',), ('defined_daily_dose',), ('activity_supp',), ('component_class',), ('target_relations',), ('biotherapeutics',), ('compound_records',), ('binding_sites',), ('compound_structural_alerts',), ('assays',), ('molecule_hierarchy',), ('molecule_synonyms',), ('molecule_hrac_classification',), ('target_components',), ('compound_properties',), ('molecule_frac_classification',), ('molecule_irac_classification',), ('molecule_atc_classification',), ('compound_structures',), ('drug_indication',), ('drug_mechanism',), ('assay_parameters',), ('activities',), ('drug_warning',), ('metabolism',), ('biotherapeutic_components',), ('assay_class_map',), ('formulations',), ('site_components',), ('indication_refs',), ('mechanism_refs',), ('activity_properties',), ('warning_refs',), ('metabolism_refs',), ('predicted_binding_domains',), ('activity_supp_map',), ('ligand_eff',), ('sqlite_stat1',)]

## Activity data loading

In [4]:
%%time
activities = pd.read_sql_query("SELECT * from activities", con)
print(activities.shape)

# rename columns to be able to track back
activities.columns=[f'activities|{x}' for x in activities.columns]

print(activities.shape)
activities.head()

(19286751, 27)
(19286751, 27)
CPU times: user 3min 39s, sys: 20.6 s, total: 4min
Wall time: 4min 5s

,activities|activity_id,activities|assay_id,activities|doc_id,activities|record_id,activities|molregno,activities|standard_relation,activities|standard_value,activities|standard_units,activities|standard_flag,activities|standard_type,...,activities|toid,activities|upper_value,activities|standard_upper_value,activities|src_id,activities|type,activities|relation,activities|value,activities|units,activities|text_value,activities|standard_text_value
0,31863,54505,6424,206172,180094,>,100000.0,nM,1,IC50,...,NaN,NaN,None,1,IC50,>,100.0,uM,None,None
1,31864,83907,6432,208970,182268,=,2500.0,nM,1,IC50,...,NaN,NaN,None,1,IC50,=,2.5,uM,None,None
2,31865,88152,6432,208970,182268,>,50000.0,nM,1,IC50,...,NaN,NaN,None,1,IC50,>,50.0,uM,None,None
3,31866,83907,6432,208987,182855,=,9000.0,nM,1,IC50,...,NaN,NaN,None,1,IC50,=,9.0,uM,None,None
4,31867,88153,6432,208987,182855,None,NaN,nM,0,IC50,...,NaN,NaN,None,1,IC50,None,NaN,uM,None,None

## Assay data loading

In [5]:
# assay data
assays = pd.read_sql_query("SELECT * from assays", con)
print(assays.shape)

# rename columns to be able to track back
assays.columns=[f'assays|{x}' for x in assays.columns]

print(assays.shape)
assays.head()

(1458215, 24)
(1458215, 24)

,assays|assay_id,assays|doc_id,assays|description,assays|assay_type,assays|assay_test_type,assays|assay_category,assays|assay_organism,assays|assay_tax_id,assays|assay_strain,assays|assay_tissue,...,assays|confidence_score,assays|curated_by,assays|src_id,assays|src_assay_id,assays|chembl_id,assays|cell_id,assays|bao_format,assays|tissue_id,assays|variant_id,assays|aidx
0,1,11087,The compound was tested for the in vitro inhib...,B,None,None,None,NaN,None,None,...,8,Autocuration,1,None,CHEMBL615117,NaN,BAO_0000019,NaN,NaN,CLD0
1,2,684,Compound was evaluated for its ability to mobi...,F,None,None,None,NaN,None,None,...,0,Autocuration,1,None,CHEMBL615118,NaN,BAO_0000219,NaN,NaN,CLD0
2,3,15453,None,B,None,None,None,NaN,None,None,...,0,Autocuration,1,None,CHEMBL615119,NaN,BAO_0000019,NaN,NaN,CLD0
3,4,17841,Binding affinity against A2 adenosine receptor...,B,None,None,Bos taurus,9913.0,None,Striatum,...,4,Autocuration,1,None,CHEMBL615120,NaN,BAO_0000249,2435.0,NaN,CLD0
4,5,17430,In vitro cell cytotoxicity against 143-B cell ...,F,None,None,Homo sapiens,9606.0,None,None,...,1,Intermediate,1,None,CHEMBL615121,163.0,BAO_0000219,NaN,NaN,CLD0

## Target data loading

In [6]:
target_dictionary = pd.read_sql_query("SELECT * from target_dictionary", con)
print(target_dictionary.shape)

# rename columns to be able to track back
target_dictionary.columns=[f'target_dictionary|{x}' for x in target_dictionary.columns]

target_dictionary.head()

(14855, 7)

,target_dictionary|tid,target_dictionary|target_type,target_dictionary|pref_name,target_dictionary|tax_id,target_dictionary|organism,target_dictionary|chembl_id,target_dictionary|species_group_flag
0,1,SINGLE PROTEIN,Maltase-glucoamylase,9606.0,Homo sapiens,CHEMBL2074,0
1,2,SINGLE PROTEIN,Sulfonylurea receptor 2,9606.0,Homo sapiens,CHEMBL1971,0
2,3,SINGLE PROTEIN,Phosphodiesterase 5A,9606.0,Homo sapiens,CHEMBL1827,0
3,4,SINGLE PROTEIN,Voltage-gated T-type calcium channel alpha-1H ...,9606.0,Homo sapiens,CHEMBL1859,0
4,5,SINGLE PROTEIN,Nicotinic acetylcholine receptor alpha subunit,6253.0,Ascaris suum,CHEMBL1884,0

In [7]:
target_components = pd.read_sql_query("SELECT * from target_components", con)
print(target_components.shape)

# rename columns to be able to track back
target_components.columns=[f'target_components|{x}' for x in target_components.columns]

target_components.head()

(13558, 4)

,target_components|tid,target_components|component_id,target_components|targcomp_id,target_components|homologue
0,11004,3090,1,0
1,11028,1166,4,0
2,11037,1888,5,0
3,11043,1294,7,0
4,11056,2159,8,0

In [8]:
component_synonyms = pd.read_sql_query("SELECT * from component_synonyms", con)
print(component_synonyms.shape)

# rename columns to be able to track back
component_synonyms.columns=[f'component_synonyms|{x}' for x in component_synonyms.columns]

component_synonyms.head()

(97172, 4)

,component_synonyms|compsyn_id,component_synonyms|component_id,component_synonyms|component_synonym,component_synonyms|syn_type
0,860862,48,Gabra-1,GENE_SYMBOL_OTHER
1,860867,49,Gabrb-3,GENE_SYMBOL_OTHER
2,860872,50,Gabrb-2,GENE_SYMBOL_OTHER
3,860877,51,CDKN5,GENE_SYMBOL_OTHER
4,860915,56,NMDAR1,GENE_SYMBOL_OTHER

## Compound data loading

In [9]:
drug_mechanism = pd.read_sql_query("SELECT * from drug_mechanism", con)
print(drug_mechanism.shape)

# rename columns to be able to track back
drug_mechanism.columns=[f'drug_mechanism|{x}' for x in drug_mechanism.columns]

drug_mechanism.head()

(6656, 14)

,drug_mechanism|mec_id,drug_mechanism|record_id,drug_mechanism|molregno,drug_mechanism|mechanism_of_action,drug_mechanism|tid,drug_mechanism|site_id,drug_mechanism|action_type,drug_mechanism|direct_interaction,drug_mechanism|molecular_mechanism,drug_mechanism|disease_efficacy,drug_mechanism|mechanism_comment,drug_mechanism|selectivity_comment,drug_mechanism|binding_site_comment,drug_mechanism|variant_id
0,13,1343810,1124,Carbonic anhydrase VII inhibitor,11060.0,NaN,INHIBITOR,1,1,1,None,None,None,NaN
1,14,1344053,675068,Carbonic anhydrase I inhibitor,10193.0,NaN,INHIBITOR,1,1,1,None,None,None,NaN
2,15,1344649,674765,Carbonic anhydrase I inhibitor,10193.0,NaN,INHIBITOR,1,1,1,Expressed in eye,None,None,NaN
3,16,1343255,1085,Carbonic anhydrase I inhibitor,10193.0,NaN,INHIBITOR,1,1,1,None,None,None,NaN
4,17,1344903,1125,Carbonic anhydrase I inhibitor,10193.0,NaN,INHIBITOR,1,1,1,Expressed in eye,None,None,NaN

In [10]:
molecule_dictionary = pd.read_sql_query("SELECT * from molecule_dictionary", con)
print(molecule_dictionary.shape)

# rename columns to be able to track back
molecule_dictionary.columns=[f'molecule_dictionary|{x}' for x in molecule_dictionary.columns]

molecule_dictionary.head()

(2157379, 31)

,molecule_dictionary|molregno,molecule_dictionary|pref_name,molecule_dictionary|chembl_id,molecule_dictionary|max_phase,molecule_dictionary|therapeutic_flag,molecule_dictionary|dosed_ingredient,molecule_dictionary|structure_type,molecule_dictionary|chebi_par_id,molecule_dictionary|molecule_type,molecule_dictionary|first_approval,...,molecule_dictionary|usan_stem,molecule_dictionary|polymer_flag,molecule_dictionary|usan_substem,molecule_dictionary|usan_stem_definition,molecule_dictionary|indication_class,molecule_dictionary|withdrawn_flag,molecule_dictionary|withdrawn_year,molecule_dictionary|withdrawn_country,molecule_dictionary|withdrawn_reason,molecule_dictionary|withdrawn_class
0,1,None,CHEMBL6329,0,0,0,MOL,NaN,Small molecule,NaN,...,None,0,None,None,None,0,NaN,None,None,None
1,2,None,CHEMBL6328,0,0,0,MOL,NaN,Small molecule,NaN,...,None,0,None,None,None,0,NaN,None,None,None
2,3,None,CHEMBL265667,0,0,0,MOL,NaN,Small molecule,NaN,...,None,0,None,None,None,0,NaN,None,None,None
3,4,None,CHEMBL6362,0,0,0,MOL,NaN,Small molecule,NaN,...,None,0,None,None,None,0,NaN,None,None,None
4,5,None,CHEMBL267864,0,0,0,MOL,NaN,Small molecule,NaN,...,None,0,None,None,None,0,NaN,None,None,None

In [11]:
molecule_atc_classification = pd.read_sql_query("SELECT * from molecule_atc_classification", con)
print(molecule_atc_classification.shape)

# rename columns to be able to track back
molecule_atc_classification.columns=[f'molecule_atc_classification|{x}' for x in molecule_atc_classification.columns]

molecule_atc_classification.head()

(4470, 3)

,molecule_atc_classification|mol_atc_id,molecule_atc_classification|level5,molecule_atc_classification|molregno
0,59409,L01EX15,2089491
1,59410,L01EX10,608601
2,59411,L01EM03,1567700
3,59412,D06BX03,579824
4,59413,L01EX13,1763584

In [12]:
atc_classification = pd.read_sql_query("SELECT * from atc_classification", con)
print(atc_classification.shape)

# rename columns to be able to track back
atc_classification.columns=[f'atc_classification|{x}' for x in atc_classification.columns]

atc_classification.head()

(5148, 10)

,atc_classification|who_name,atc_classification|level1,atc_classification|level2,atc_classification|level3,atc_classification|level4,atc_classification|level5,atc_classification|level1_description,atc_classification|level2_description,atc_classification|level3_description,atc_classification|level4_description
0,sodium fluoride,A,A01,A01A,A01AA,A01AA01,ALIMENTARY TRACT AND METABOLISM,STOMATOLOGICAL PREPARATIONS,STOMATOLOGICAL PREPARATIONS,Caries prophylactic agents
1,sodium monofluorophosphate,A,A01,A01A,A01AA,A01AA02,ALIMENTARY TRACT AND METABOLISM,STOMATOLOGICAL PREPARATIONS,STOMATOLOGICAL PREPARATIONS,Caries prophylactic agents
2,olaflur,A,A01,A01A,A01AA,A01AA03,ALIMENTARY TRACT AND METABOLISM,STOMATOLOGICAL PREPARATIONS,STOMATOLOGICAL PREPARATIONS,Caries prophylactic agents
3,stannous fluoride,A,A01,A01A,A01AA,A01AA04,ALIMENTARY TRACT AND METABOLISM,STOMATOLOGICAL PREPARATIONS,STOMATOLOGICAL PREPARATIONS,Caries prophylactic agents
4,combinations,A,A01,A01A,A01AA,A01AA30,ALIMENTARY TRACT AND METABOLISM,STOMATOLOGICAL PREPARATIONS,STOMATOLOGICAL PREPARATIONS,Caries prophylactic agents

In [ ]:
# atc_classification = pd.read_sql_query("SELECT * from atc_classification", con)
# atc_classification.to_csv('/home/jovyan/projects/P50_ChEMBL/csv/atc_classification_db30.csv',index=False)

## Concatenate information

* activities_final:<br> 
'activities|activity_id', 'activities|assay_id', 'activities|molregno',
'activities|pchembl_value', 'activities|type', 'activities|standard_relation', 'activities|standard_value',
'activities|standard_units', 'activities|standard_flag',
'activities|standard_type', 'activities|activity_comment',
'assays|description','assays|assay_type','assays|tid', 'assays|confidence_score','assays|curated_by','assays|chembl_id',<br>
<br>
* targets_final:<br>
'target_dictionary|tid','target_dictionary|target_type','target_dictionary|pref_name','target_dictionary|organism','target_dictionary|chembl_id',
'component_synonyms|component_synonym', 'component_synonyms|syn_type'<br>
<br>
* molecule_dictionary:<br>
'molecule_dictionary|molregno', 'molecule_dictionary|pref_name','molecule_dictionary|chembl_id', 'molecule_dictionary|max_phase', 'molecule_dictionary|molecule_type','molecule_dictionary|oral',
'molecule_dictionary|parenteral', 'molecule_dictionary|topical','molecule_dictionary|black_box_warning','molecule_dictionary|natural_product'<br>
<br>    
* drug_mechanism:<br>
'drug_mechanism|molregno','drug_mechanism|mechanism_of_action','drug_mechanism|tid','drug_mechanism|action_type',
<br>
* molecule_atc_classification:<br>
'molecule_atc_classification|mol_atc_id','molecule_atc_classification|level5','molecule_atc_classification|molregno'
<br>
* atc_classification:<br>
'atc_classification|who_name', 'atc_classification|level1','atc_classification|level2', 'atc_classification|level3',
'atc_classification|level4', 'atc_classification|level5','atc_classification|level1_description','atc_classification|level2_description',
'atc_classification|level3_description','atc_classification|level4_description'

In [13]:
# merge activities and assays data
final_df = activities.merge(assays,how='left',left_on='activities|assay_id',right_on='assays|assay_id')
final_df = final_df[['activities|activity_id', 'activities|assay_id', 'activities|molregno',
                             'activities|pchembl_value', 'activities|type', 'activities|standard_relation', 'activities|standard_value',
                             'activities|standard_units', 'activities|standard_flag','activities|standard_type', 'activities|activity_comment',
                             'assays|description','assays|assay_type','assays|tid', 'assays|confidence_score','assays|curated_by','assays|chembl_id']]
print(f'activities+assays: {final_df.shape}')

# merge activities and drug_mechanism based on 'molregno': how='outer' to capture all
final_df = final_df.merge(drug_mechanism[['drug_mechanism|molregno','drug_mechanism|mechanism_of_action','drug_mechanism|tid','drug_mechanism|action_type',]],
                          how='outer',left_on=['activities|molregno','assays|tid'],right_on=['drug_mechanism|molregno','drug_mechanism|tid'])
print(f'added drug mechanism: {final_df.shape}')

## remake molregno column by combining
ind = final_df[(final_df['drug_mechanism|molregno']==final_df['drug_mechanism|molregno'])& \
         (final_df['activities|molregno']!=final_df['activities|molregno'])].index
final_df['activities_drug_mechanism|molregno']=final_df['activities|molregno'].copy()
final_df.loc[ind,'activities_drug_mechanism|molregno']=final_df.loc[ind,'drug_mechanism|molregno']
print(sum(final_df['activities_drug_mechanism|molregno']==final_df['activities_drug_mechanism|molregno']))
del ind

## remake tid column by combining
ind = final_df[(final_df['drug_mechanism|tid']==final_df['drug_mechanism|tid'])& \
         (final_df['assays|tid']!=final_df['assays|tid'])].index
final_df['assays_drug_mechanism|tid']=final_df['assays|tid'].copy()
final_df.loc[ind,'assays_drug_mechanism|tid']=final_df.loc[ind,'drug_mechanism|tid']
print(sum(final_df['assays_drug_mechanism|tid']==final_df['assays_drug_mechanism|tid']))


# merge compound informations
final_df = final_df.merge(molecule_dictionary[['molecule_dictionary|molregno', 'molecule_dictionary|pref_name','molecule_dictionary|chembl_id', 'molecule_dictionary|max_phase', 
                                               'molecule_dictionary|molecule_type','molecule_dictionary|oral','molecule_dictionary|parenteral', 'molecule_dictionary|topical',
                                               'molecule_dictionary|black_box_warning','molecule_dictionary|natural_product']],
                          how='left',left_on='activities_drug_mechanism|molregno',right_on='molecule_dictionary|molregno')

final_df = final_df.merge(molecule_atc_classification[['molecule_atc_classification|molregno','molecule_atc_classification|level5']],
                          how='left',left_on='activities_drug_mechanism|molregno',right_on='molecule_atc_classification|molregno')

final_df = final_df.merge(atc_classification[['atc_classification|level1','atc_classification|level2','atc_classification|level3','atc_classification|level4','atc_classification|level5',
                                              'atc_classification|level1_description','atc_classification|level2_description',
                                              'atc_classification|level3_description','atc_classification|level4_description','atc_classification|who_name']],
                          how='left',left_on='molecule_atc_classification|level5',right_on='atc_classification|level5')
print(f'added compound info: {final_df.shape}')

# merge targets
## merging target dataframes first (to link tid with gene symbol)
targets_final = target_dictionary.merge(target_components,how='left',left_on='target_dictionary|tid',right_on='target_components|tid')
targets_final = targets_final.merge(component_synonyms,how='left',left_on='target_components|component_id',right_on='component_synonyms|component_id')
print(targets_final['component_synonyms|syn_type'].value_counts())

## selecting targets which have 'gene symbol'
## syn_type == 'GENE_SYMBOL'
targets_final = targets_final[targets_final['component_synonyms|syn_type']=='GENE_SYMBOL']

## merge
final_df = final_df.merge(targets_final[['target_dictionary|tid','target_dictionary|target_type','target_dictionary|pref_name','target_dictionary|organism','target_dictionary|chembl_id',
                                         'component_synonyms|component_synonym', 'component_synonyms|syn_type']],
                          how='left',left_on='assays_drug_mechanism|tid',right_on='target_dictionary|tid')

print(f'added targets info: {final_df.shape}')
final_df.head()

activities+assays: (19286751, 17)
added drug mechanism: (19291779, 21)
19291779
19291382
added compound info: (20181918, 45)
UNIPROT              55495
GENE_SYMBOL_OTHER    39293
GENE_SYMBOL          13028
EC_NUMBER             7943
Name: component_synonyms|syn_type, dtype: int64
added targets info: (21292684, 52)

,activities|activity_id,activities|assay_id,activities|molregno,activities|pchembl_value,activities|type,activities|standard_relation,activities|standard_value,activities|standard_units,activities|standard_flag,activities|standard_type,...,atc_classification|level3_description,atc_classification|level4_description,atc_classification|who_name,target_dictionary|tid,target_dictionary|target_type,target_dictionary|pref_name,target_dictionary|organism,target_dictionary|chembl_id,component_synonyms|component_synonym,component_synonyms|syn_type
0,31863.0,54505.0,180094.0,NaN,IC50,>,100000.00,nM,1.0,IC50,...,NaN,NaN,NaN,63.0,SINGLE PROTEIN,DNA topoisomerase II alpha,Homo sapiens,CHEMBL1806,TOP2A,GENE_SYMBOL
1,31864.0,83907.0,182268.0,5.60,IC50,=,2500.00,nM,1.0,IC50,...,NaN,NaN,NaN,11653.0,SINGLE PROTEIN,Heparanase,Homo sapiens,CHEMBL3921,HPSE,GENE_SYMBOL
2,2224237.0,531583.0,182268.0,5.60,pIC50,=,2511.89,nM,1.0,IC50,...,NaN,NaN,NaN,11653.0,SINGLE PROTEIN,Heparanase,Homo sapiens,CHEMBL3921,HPSE,GENE_SYMBOL
3,31865.0,88152.0,182268.0,NaN,IC50,>,50000.00,nM,1.0,IC50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,31866.0,83907.0,182855.0,5.05,IC50,=,9000.00,nM,1.0,IC50,...,NaN,NaN,NaN,11653.0,SINGLE PROTEIN,Heparanase,Homo sapiens,CHEMBL3921,HPSE,GENE_SYMBOL

## Save the data frame above for access to non-human entries

## Filtering drugs targeting human molecules

In [30]:
final_df = final_df[final_df['target_dictionary|organism']=='Homo sapiens']
final_df.shape

(6708016, 53)

## Add target class

- Based on [IDG Protein list](https://druggablegenome.net/IDGProteinList)
- add 'Ion channel' from [HGNC, GID:177](https://www.genenames.org/data/genegroup/#!/group/177)
- add 'GPCR' from [HGNC, GID:139](https://www.genenames.org/data/genegroup/#!/group/139)
- add 'NHR' (Nuclear Hormone Receptors) from [HGNC, GID:71](https://www.genenames.org/data/genegroup/#!/group/71)

In [31]:
# create dictionary for protein classes
idg = pd.read_csv('IDG_TargetList_Y4.csv')

targetclass_dict={}
for c in set(idg['IDGFamily']):
    targetclass_dict[c]=list(idg[idg['IDGFamily']==c]['Gene'])

ion = pd.read_csv('HGNC_GID177_Ion-channels.txt',sep='\t')
gpcr = pd.read_csv('HGNC_GID139_G-protein-coupled-receptors.txt',sep='\t')
nr = pd.read_csv('HGNC_GID71_Nuclear-hormone-receptors.txt',sep='\t')

targetclass_dict['Ion Channel']=list(set(targetclass_dict['Ion Channel']+list(ion['Approved symbol'])))
targetclass_dict['GPCR']=list(set(targetclass_dict['GPCR']+list(gpcr['Approved symbol'])))
targetclass_dict['NHR']=list(nr['Approved symbol'].unique())
targetclass_dict.keys()

dict_keys(['Kinase', 'GPCR', 'Ion Channel', 'NHR'])

In [32]:
# assin protein class to each target
def which_class(dictionary, value):
    out='none'
    for k in dictionary.keys():
        if value in dictionary[k]:
            if out=='none':
                out=k
            else:
                out=f'{out};{k}'
    return out

# add target class
final_df['target_class']=final_df['component_synonyms|component_synonym'].copy()
final_df['target_class']=[which_class(targetclass_dict,t) for t in final_df['target_class']]
final_df['target_class'].value_counts()

/home/jovyan/my-conda-envs/cellpymc/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/home/jovyan/my-conda-envs/cellpymc/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

none           5347947
GPCR            903731
NHR             177300
Ion Channel     174983
Kinase          104055
Name: target_class, dtype: int64

## Save

In [34]:
%%time
final_df.to_pickle('chembl_30_merged_genesymbols_humans.pkl')

CPU times: user 25.7 s, sys: 5.28 s, total: 31 s
Wall time: 50.3 s

## Session info

In [35]:
import session_info
session_info.show()